package me.ducky.projectg.catalog.catalogs;

import me.ducky.projectg.catalog.enums.GunClass;
import me.ducky.projectg.catalog.enums.Rarity;
import me.ducky.projectg.catalog.items.GunItem;

import java.util.ArrayList;
import java.util.List;

public class GunCatalog {
    public static final List<GunItem> LIST;

    static {
        // TODO buff
        LIST = new ArrayList<>();
        LIST.add(new GunItem("SOCOM M4A1", GunClass.ASSAULT_RIFLE, "MW_SOCOM_M4A1", "MW_SOCOM_MAG", 12, Rarity.COMMON));
        LIST.add(new GunItem("ARX-160", GunClass.ASSAULT_RIFLE, "MW_ARX160", "MW_M4A1MAG_2", 12, Rarity.COMMON));
        LIST.add(new GunItem("C8 SFW", GunClass.ASSAULT_RIFLE, "MW_C8_SFW", "MW_M4A1MAG_2", 12, Rarity.COMMON));
        LIST.add(new GunItem("BREN A1", GunClass.ASSAULT_RIFLE, "MW_CZ805_BREN_A1", "MW_M4A1MAG_2", 12, Rarity.COMMON));
        LIST.add(new GunItem("AK-74", GunClass.ASSAULT_RIFLE, "MW_AK74", "MW_AK74MAG", 12, Rarity.COMMON));
        LIST.add(new GunItem("AK-15", GunClass.ASSAULT_RIFLE, "MW_AK15", "MW_AK15MAG_2", 12, Rarity.COMMON));
        LIST.add(new GunItem("M16A4", GunClass.ASSAULT_RIFLE, "MW_M16A4", "MW_M4A1MAG_2", 12, Rarity.UNCOMMON));
        LIST.add(new GunItem("Remington ACR", GunClass.ASSAULT_RIFLE, "MW_ACR", "MW_M4A1MAG_2", 12, Rarity.UNCOMMON));
        LIST.add(new GunItem("Mk 16 SCAR-L", GunClass.ASSAULT_RIFLE, "MW_SCAR_L", "MW_M4A1MAG_2", 12, Rarity.UNCOMMON));
        LIST.add(new GunItem("HK G36K", GunClass.ASSAULT_RIFLE, "MW_G36K", "MW_G36CMAG_2", 12, Rarity.UNCOMMON));
        LIST.add(new GunItem("AK-12", GunClass.ASSAULT_RIFLE, "MW_KALASHNIKOV_AK12", "MW_AK15MAG_2", 12, Rarity.UNCOMMON));
        LIST.add(new GunItem("HK G95", GunClass.ASSAULT_RIFLE, "MW_HK_G95", "MW_M4A1MAG_2", 12, Rarity.UNCOMMON));
        LIST.add(new GunItem("K2C1", GunClass.ASSAULT_RIFLE, "MW_K2C1", "MW_M4A1MAG_2", 12, Rarity.RARE));
        LIST.add(new GunItem("NV4", GunClass.ASSAULT_RIFLE, "MW_NV4", "MW_BULLET556X45", 384, Rarity.RARE));
        LIST.add(new GunItem("MA37 ICWS", GunClass.ASSAULT_RIFLE, "MW_MA37_ICWS", "MW_BULLET762X51", 384, Rarity.RARE));
        LIST.add(new GunItem("M41A", GunClass.ASSAULT_RIFLE, "MW_M41A", "MW_BULLET10MM", 384, Rarity.RARE));
        LIST.add(new GunItem("AUG A1", GunClass.ASSAULT_RIFLE, "MW_STEYR_AUG_A1", "MW_M4A1MAG_2", 12, Rarity.RARE));
        LIST.add(new GunItem("HK G11", GunClass.ASSAULT_RIFLE, "MW_G11", "MW_G11MAG", 12, Rarity.RARE));
        LIST.add(new GunItem("AK-103", GunClass.ASSAULT_RIFLE, "MW_AK103_BULLPUP", "MW_AK47MAG", 12, Rarity.RARE));
        LIST.add(new GunItem("M4A4 Asiimov", GunClass.ASSAULT_RIFLE, "MW_ASIIMOV_M4A1", "MW_M4ASIIMOVMAG", 12, Rarity.EPIC));
        LIST.add(new GunItem("AKM Vulcan", GunClass.ASSAULT_RIFLE, "MW_AKM_VULCAN", "MW_AKMVULCANMAG", 12, Rarity.EPIC));
        LIST.add(new GunItem("AAC Honey Badger", GunClass.ASSAULT_RIFLE, "MW_AAC_HONEY_BADGER", "MW_HONEYBADGERMAG_2", 12, Rarity.EPIC));
        LIST.add(new GunItem("FN F2000", GunClass.ASSAULT_RIFLE, "MW_F2000", "MW_M4A1MAG_2", 12, Rarity.EPIC));
        LIST.add(new GunItem("VOLK", GunClass.ASSAULT_RIFLE, "MW_VOLK", "MW_ENERGYCASE", 384, Rarity.EPIC));
        LIST.add(new GunItem("TYPE-2", GunClass.ASSAULT_RIFLE, "MW_TYPE2", "MW_ENERGYCASE", 384, Rarity.LEGENDARY));
        LIST.add(new GunItem("OSIPR", GunClass.ASSAULT_RIFLE, "MW_OSIPR", "MW_BULLET762X51", 384, Rarity.LEGENDARY));
        LIST.add(new GunItem("SCAR-H", GunClass.BATTLE_RIFLE, "MW_SCAR_H_CQC", "MW_SCARHMAG_2", 12, Rarity.COMMON));
        LIST.add(new GunItem("KBP 9A_91", GunClass.BATTLE_RIFLE, "MW_KBP_9A91", "MW_KBP9A91MAG_2", 12, Rarity.UNCOMMON));
        LIST.add(new GunItem("SR-3", GunClass.BATTLE_RIFLE, "MW_SR3_VIKHR", "MW_VSSVINTOREZMAG_2", 12, Rarity.UNCOMMON));
        LIST.add(new GunItem("FN FAL", GunClass.BATTLE_RIFLE, "MW_FNFAL", "MW_AK47MAG", 12, Rarity.RARE));
        LIST.add(new GunItem("M8A7", GunClass.BATTLE_RIFLE, "MW_M8A7", "MW_BULLET556X45", 12, Rarity.RARE));
        LIST.add(new GunItem("MA5D ICWS", GunClass.BATTLE_RIFLE, "MW_MA5D", "MW_BULLET762X51", 384, Rarity.EPIC));
        LIST.add(new GunItem("BR-55", GunClass.BATTLE_RIFLE, "MW_BR55", "MW_BULLET762X51", 384, Rarity.EPIC));
        LIST.add(new GunItem("AR-10 Super SASS", GunClass.DMR, "MW_AR10_SUPER_SASS", "MW_M110MAG_2", 6, Rarity.COMMON));
        LIST.add(new GunItem("Mk14", GunClass.DMR, "MW_MK14_EBR", "MW_MK14EBRMAG_2", 6, Rarity.COMMON));
        LIST.add(new GunItem("M1941 Johnson Rifle", GunClass.DMR, "MW_M1941_JOHNSON_RIFLE", "MW_BULLET3006SPRINGFIELD", 192, Rarity.UNCOMMON));
        LIST.add(new GunItem("M110 SASS", GunClass.DMR, "MW_M110_SASS", "MW_M110MAG_2", 6, Rarity.UNCOMMON));
        LIST.add(new GunItem("HK SL8", GunClass.DMR, "MW_SL8", "MW_G36CMAG_2", 6, Rarity.RARE));
        LIST.add(new GunItem("M1 Garand", GunClass.DMR, "MW_M1_GARAND", "MW_BULLET3006SPRINGFIELD", 192, Rarity.RARE));
        LIST.add(new GunItem("G43 Gewehr", GunClass.DMR, "MW_G43_GEWEHR", "MW_G43_GEWEHR_MAG", 6, Rarity.RARE));
        LIST.add(new GunItem("Mare's Leg", GunClass.DMR, "MW_MARES_LEG", "MW_BULLET44", 192, Rarity.RARE));
        LIST.add(new GunItem("M392", GunClass.DMR, "MW_M392", "MW_BULLET762X51", 192, Rarity.EPIC));
        LIST.add(new GunItem("VSS Vintorez", GunClass.DMR, "MW_VSS_VINTOREZ", "MW_VSSVINTOREZMAG_2", 6, Rarity.EPIC));
        LIST.add(new GunItem("TYPE-51", GunClass.DMR, "MW_TYPE51", "MW_ENERGYCASE", 192, Rarity.LEGENDARY));
        LIST.add(new GunItem("M249", GunClass.LMG, "MW_M249", "MW_M249MAG", 6, Rarity.COMMON));
        LIST.add(new GunItem("Stoner A1", GunClass.LMG, "MW_STONERA1", "MW_STONERMAG", 6, Rarity.UNCOMMON));
        LIST.add(new GunItem("MG-42", GunClass.LMG, "MW_MG42", "MW_MG42MAG_2", 6, Rarity.UNCOMMON));
        LIST.add(new GunItem("M1941 Johnson LMG", GunClass.LMG, "MW_M1941_JOHNSON", "MW_JOHNSONMAG", 12, Rarity.RARE));
        LIST.add(new GunItem("HAR-27", GunClass.LMG, "MW_HAR_27", "MW_BULLET556X45", 384, Rarity.EPIC));
        LIST.add(new GunItem("M56 ESG", GunClass.LMG, "MW_M56", "MW_BULLET556X45", 384, Rarity.LEGENDARY));
        LIST.add(new GunItem("HK MP7A1", GunClass.SMG, "MW_MP7A1", "MW_MP7MAG", 12, Rarity.COMMON));
        LIST.add(new GunItem("UMP45", GunClass.SMG, "MW_UMP_45", "MW_UMP45MAG", 12, Rarity.COMMON));
        LIST.add(new GunItem("APC9", GunClass.SMG, "MW_APC9", "MW_APC9MAG", 12, Rarity.UNCOMMON));
        LIST.add(new GunItem("UZI", GunClass.SMG, "MW_UZI", "MW_UZIMAG_2", 12, Rarity.UNCOMMON));
        LIST.add(new GunItem("P90", GunClass.SMG, "MW_P90", "MW_P90MAG", 12, Rarity.RARE));
        LIST.add(new GunItem("Kriss Vector", GunClass.SMG, "MW_KRISS_VECTOR", "MW_VECTORMAG", 12, Rarity.RARE));
        LIST.add(new GunItem("Scorpion EVO3 A1", GunClass.SMG, "MW_SCORPION_EVO3_A1", "MW_SCORPIONMAG", 12, Rarity.RARE));
        LIST.add(new GunItem("MAC-10", GunClass.SMG, "MW_MAC10", "MW_MAC10MAG", 12, Rarity.RARE));
        LIST.add(new GunItem("M20 PDW", GunClass.SMG, "MW_M20", "MW_BULLET9X19MM", 384, Rarity.EPIC));
        LIST.add(new GunItem("Thompson", GunClass.SMG, "MW_M1928_THOMPSON", "MW_M1928MAG", 12, Rarity.EPIC));
        LIST.add(new GunItem("M1014", GunClass.SHOTGUN, "MW_M1014", "MW_SHOTGUN12GAUGE", 32, Rarity.COMMON));
        LIST.add(new GunItem("KS-23", GunClass.SHOTGUN, "MW_KS23", "MW_SHOTGUN4G", 32, Rarity.COMMON));
        LIST.add(new GunItem("Remington-870", GunClass.SHOTGUN, "MW_REMINGTON870", "MW_SHOTGUN12GAUGE", 32, Rarity.UNCOMMON));
        LIST.add(new GunItem("Spas-12", GunClass.SHOTGUN, "MW_SPAS_12", "MW_SHOTGUN12GAUGE", 32, Rarity.UNCOMMON));
        LIST.add(new GunItem("Origin-12", GunClass.SHOTGUN, "MW_ORIGIN12", "MW_ORIGIN12MAG", 12, Rarity.RARE));
        LIST.add(new GunItem("CSA-16", GunClass.SHOTGUN, "MW_CSA16", "MW_SHOTGUN4G", 32, Rarity.RARE));
        LIST.add(new GunItem("Saiga 12", GunClass.SHOTGUN, "MW_SAIGA12", "MW_SAIGAMAG_2", 12, Rarity.EPIC));
        LIST.add(new GunItem("M45", GunClass.SHOTGUN, "MW_M45", "MW_SHOTGUN12GAUGE", 32, Rarity.EPIC));
        LIST.add(new GunItem("SSG-42 MkII-DS", GunClass.SHOTGUN, "MW_SSG42", "MW_SHOTGUN12GAUGE", 32, Rarity.LEGENDARY));
        LIST.add(new GunItem("AS50", GunClass.SNIPER_RIFLE, "MW_AS50", "MW_AS50MAG_2", 6, Rarity.COMMON));
        LIST.add(new GunItem("L96A1", GunClass.SNIPER_RIFLE, "MW_L96A1", "MW_L96A1MAG_2", 6, Rarity.COMMON));
        LIST.add(new GunItem("Izhmash SV-98", GunClass.SNIPER_RIFLE, "MW_SV98", "MW_SV98MAG_2", 6, Rarity.UNCOMMON));
        LIST.add(new GunItem("M40A6", GunClass.SNIPER_RIFLE, "MW_M40A6", "MW_M40A6MAG_2", 6, Rarity.UNCOMMON));
        LIST.add(new GunItem("M200 Intervention", GunClass.SNIPER_RIFLE, "MW_M200_INTERVENTION", "MW_INTERVENTIONMAG", 6, Rarity.RARE));
        LIST.add(new GunItem("Remington-700", GunClass.SNIPER_RIFLE, "MW_REMINGTON_700", "MW_R700MAG", 6, Rarity.RARE));
        LIST.add(new GunItem("M1903 Springfield", GunClass.SNIPER_RIFLE, "MW_SPRINGFIELD", "MW_BULLET3006SPRINGFIELD", 64, Rarity.RARE));
        LIST.add(new GunItem("M82 Barrett", GunClass.SNIPER_RIFLE, "MW_M82_BARRETT", "MW_M82MAG_2", 6, Rarity.EPIC));
        LIST.add(new GunItem("AX-50", GunClass.SNIPER_RIFLE, "MW_AX50", "MW_AX50MAG", 6, Rarity.EPIC));
        LIST.add(new GunItem("Krag Jorgensen", GunClass.SNIPER_RIFLE, "MW_KRAG_JORGENSEN", "MW_BULLET8X58", 64, Rarity.EPIC));
        LIST.add(new GunItem("SRS-99 AMSR", GunClass.SNIPER_RIFLE, "MW_SRS99", "MW_BULLET762X51", 64, Rarity.LEGENDARY));
        LIST.add(new GunItem("NTW-20", GunClass.SNIPER_RIFLE, "MW_NTW_20", "MW_NTW20MAG", 3, Rarity.LEGENDARY));
        LIST.add(new GunItem("Glock-18C", GunClass.SECONDARY, "MW_GLOCK_18C", "MW_GLOCK18CMAG_2", 12, Rarity.COMMON));
        LIST.add(new GunItem("CPX-2", GunClass.SECONDARY, "MW_SCCY_CPX_2", "MW_M9MAG30", 12, Rarity.COMMON));
        LIST.add(new GunItem("M6C SOCOM", GunClass.SECONDARY, "MW_M6C_SOCOM", "MW_BULLET9X19MM", 192, Rarity.UNCOMMON));
        LIST.add(new GunItem("PP-91 Kedr", GunClass.SECONDARY, "MW_PP91_KEDR", "MW_KEDRMAG_2", 12, Rarity.RARE));
        LIST.add(new GunItem("Frommer Stop", GunClass.SECONDARY, "MW_FROMMER_STOP", "MW_FROMMERSTOPMAG", 12, Rarity.RARE));
        LIST.add(new GunItem("ESA-23", GunClass.SECONDARY, "MW_ESA23", "MW_ENERGYCASE", 192, Rarity.RARE));
        LIST.add(new GunItem("Taurus Hunter", GunClass.SECONDARY, "MW_TAURUS_RAGING_HUNTER", "MW_BULLET44", 64, Rarity.RARE));
        LIST.add(new GunItem("P10", GunClass.SECONDARY, "MW_P10", "MW_BULLET10MM", 192, Rarity.EPIC));
        LIST.add(new GunItem("The Dechard", GunClass.SECONDARY, "MW_THE_DECHARD", "MW_BULLET556X45", 64, Rarity.EPIC));
        LIST.add(new GunItem("Desert Eagle", GunClass.SECONDARY, "MW_DESERT_EAGLE", "MW_DESERTEAGLEMAG", 6, Rarity.EPIC));
        LIST.add(new GunItem("M17", GunClass.SECONDARY, "MW_M17", "MW_M17MAG", 12, Rarity.LEGENDARY));
        LIST.add(new GunItem("G2 Contender", GunClass.SECONDARY, "MW_G2_CONTENDER", "MW_BULLET4570", 64, Rarity.LEGENDARY));
        LIST.add(new GunItem("Chainsaw", GunClass.SECONDARY, "MW_CHAINSAW", "MW_FUELCELL", 1, Rarity.LEGENDARY));
        LIST.add(new GunItem("Nether Blaster", GunClass.SPECIAL, "TECHGUNS_NETHERBLASTER", "TECHGUNS_ITEMSHARED", 12, Rarity.LEGENDARY));
        LIST.add(new GunItem("Laser Pistol", GunClass.SPECIAL, "TECHGUNS_LASERPISTOL", "TECHGUNS_ITEMSHARED", 1, Rarity.LEGENDARY));
    }
}
